### ISSUE TITLE
Implement containsKey check to ensure animation exists

### ISSUE THREAD

**Issue by JaredPoetter** [4950/DirtyGame#11]
Every time the code looks into the Dictionary of animations or offsets, use the method containsKey to see if the key is in the Dictionary.

Instead of throwing an exception:
- have the program draw a obvious graphic to show the user that there is something wrong with the key they entered
- Also output in the Logger that there was a problem with the key they provided

**Comment by mplewis** [comment]
I don't think we want to turn runtime exceptions into caught runtime errors, personally. If something doesn't work, it should fail hard and very visibly so that we can fix it immediately.

Am I right in thinking that these errors might show up when changes are made but should never show up in a proper production build? These keys are determined at compile time, not runtime, right?

**Comment by bkern24** [comment]
If i am understanding this correctly i have to agree with matt on this one. If for some reason our code recieved an incorrect key we wouldnt want to allow the game to continue as it may then error elsewhere making it harder to find  the root cause.

**Comment by sturmE** [comment]
Agreed.

**Comment by JaredPoetter** [comment]
The keys that I am referring to are the names you give to each animation in the XML file. So the keys are defined by the developer but are loaded at runtime so there is no way for the compiler to know if that key is going to be there or not. Did one of you have a better idea for this so that it can be caught at compile time?

**Comment by sturmE** [comment]
O compile time. The only way I can think of is doing the enumeration that I suggested to you the other day.

**Comment by JaredPoetter** [comment]
But you cannot create an enumeration at runtime. So the only option that I can think of is to have a set of N animations that can be in a sprites animation and create an enumeration for all of those animations. But this will limit us to those N animations and what happens if one of the sheets does not have an animation for one of the N. Now we are back at square one, I am just going to draw something obviously wrong and log the error.

**Comment by mplewis** [comment]
That's fine with me. I don't really care one way or the other about the animation implementation.

However, if there's a bad sprite or the animation is wrongly implemented, I want the program to crash hard, not log a soft error to console. If there's a problem with an animation we should fix it instead of putting in a placeholder. Throwing an exception will help us find what's going wrong by forcing handling of the exception, for example.

I hope I understand how exceptions work in C#.

**Comment by JaredPoetter** [comment]
Ok I will have to look into how exceptions work in C# because I have not used them in C# either.

I was also was thinking about a straight forward way on how to specify the animations like Direction string + Action string. So for attacking to the left you would pass in the string "Left" + "Attack" will give you the left attack animation.

Does that sound like a good idea?

**Comment by mplewis** [comment]
That definitely sounds like a case in which two enums would be nice -- a
`Direction` enum and an `Action` enum.

**Comment by sturmE** [comment]
You can even go further and compose a "sprite" of multiple sprites (ex. head sprite, body sprite, legs sprite). Then you can animate each body part.

Of course all this stuff is future stuff.

**Comment by AOEChamp** [comment]
Missing animations and similar criteria are akin to what assert statements would be in c++. However, since we plan to deploy this game in the near future, I would suggest we avoid throwing exceptions(as one would not include asserts in a deployed c++ app). We can handle this situation either by accessing the dictionary and catching errors, or by checking whether said animation exists before hand. Checking is the preferable approach. Exceptions should be left for unavoidable or uncommon errors, and caught as needed(such as file io). Data verification is better done with checks than exceptions. Then we can log errors, and deal with them as needed. In a large project, such minor errors can be quite commonplace(because we can't verify content as well as code), and we can't afford to crash the game every time one shows up.

**Comment by JaredPoetter** [comment]
Going through all the old tickets and closing ones that are done or not needed.
