### ISSUE TITLE
Secure more spritesheets

### ISSUE THREAD

**Issue by Quillwerth** [4950/DirtyGame#113]
Without this, the game is unplayable. With many different types of enemies, the threats each pose must be apparent at a glance. This is not a matter of mere ascetics, this is a matter of comprehensibility.

**Comment by JaredPoetter** [comment]
Just to let you know when you are going to set up the animations because there is an XML file format that you have to follow to import the sprite sheet animations. I am hoping that my animation code will work for your defined animations because I have only tested it on a small hand full of spritesheets.

**Comment by JaredPoetter** [comment]
Patrick, one note of advise when you are looking for spritesheets for the game make sure that you either create all of them the same way or find them from the same source. The reason you need to take this into account is that Brandon and I ran into a problem when we tried to get a second sprite into the world from another source it showed up a fraction the size even though it was the same pixel count for the two sprites, i.e. 50 x 50. I checked the meta data of each file and they were the same file type, color definitions, dpi values. You might want to talk to Baylor about this because there might be a reason that the sprites were coming up as different sizes. I really just wanted to make sure you had this in mind when you find/create sprites.

Also I think that we should make a standard size for each type of monster/enemy so that we do not have to worry about a sniper getting becoming bigger when it is a fire sniper vs a fast sniper. Each of the types like sniper and suicide bomber can be different sizes. That size can be anything but we just have to stick with whatever we pick from the beginning to prevent any problems.

Once again let me know if you have any questions.

**Comment by lingqingmeng** [comment]
I'de like to work on this Today, as we discussed in the Design team meeting Saturday, so feel free to re-assign the work to me (not sure how to do that in github). 

EDIT: Figured out how to reassign

**Comment by JaredPoetter** [comment]
I am thinking that there are going to be multiple parts to this ticket.
Part 1: Find the spritesheets to use. Try to make them all from the same game or artist.
Part 2: Create the code, aka XML, for the sprites.
Part 3: Making sure they are the correct size and scale.
So we are going to need to discuss this.

**Comment by lingqingmeng** [comment]
Sounds good, I'm all up for more discussion to clarify this better. Would it be better to do in person? If you can email me the basics I could research/expand on that too.

I'm reading up on the code that has to deal with Sprites. So far I've seen that .png and .xml are the most commonly used Data sources. 

So in order for spritesheets to be usable, do they have to have the .xml file with it? If a sprite has an animation (for example, a person shooting a bow would have 10 frames or so of animation, where the bow string is drawn back and then released), do they need all the frames with that animation or is that handled by our monogame framework? Also, do we create the xml files or should they be included in the sprite package?

**Comment by lingqingmeng** [comment]
Are we able to use this resource? 
http://gaurav.munjal.us/Universal-LPC-Spritesheet-Character-Generator/#

GNU public license: http://gaurav.munjal.us/Universal-LPC-Spritesheet-Character-Generator/LICENSE

I was able to generate this using it. It basically fulfills all our needs if we're able to use their images since we can generate basically any possibility (in the realm of medieval sprites).
![dfsdf](https://f.cloud.github.com/assets/5965718/2066569/6103d72a-8cf0-11e3-8e16-af39e67dbbfd.png)

**Comment by JaredPoetter** [comment]
It will be better for me to explain the spritesheet code in person because there are a lot of little things to talk about. You can read through this it should get you started with understanding what the XML is used for; https://github.com/4950/ShittyPrototype/wiki/Animation.

**Comment by JaredPoetter** [comment]
Also the XML is just a file structure that I came up with so you will not find anything like the XML with a spritesheet online.

**Comment by JaredPoetter** [comment]
Another note is that we are only needing to have simple sprites for right now to get the game to look presentable in an alpha state. Once we start getting more monsters implemented in the game and some of the other features into the game we need to go back through and put in different animations for different weapons and monsters.

**Comment by AOEChamp** [comment]
That sprite generation site might be perfect for creating monsters

**Comment by JaredPoetter** [comment]
I will work on writing the SpriteSheet XML this morning that should work for all of the spritesheets that are generated from the site that Ling found. I figured instead of someone else trying to learn how to do the XML for animation I would just do it because I would be one of the fastest at it because I wrote the animation code.
