### ISSUE TITLE
Implementing animation direction into player and monster movement

### ISSUE THREAD

**Issue by JaredPoetter** [4950/DirtyGame#23]
I was wondering if anyone had any thoughts on how to do this. I have a couple of ideas but I want to find an idea that will make it as flexible as possible.
- DirectionComponent to store the direction of the sprite. The AnimationSystem would take this in as part of its aspect. It would then be able to pass the information onto the onto the AnimationComponent.
- AnimationComponent being required in the aspect for the PlayerSystem and MonsterSystem. 
- All systems that have the SpatialComponent will require the AnimationComponent so you can set the direction of the animation.
- The above can be flipped around. All systems that have the AnimationComponent will require the SpatialComponent so you can set the direction of the animation.

**Comment by sturmE** [comment]
I think the idea of a direction component is good. Maybe later on we can combine that with other components. I dont like the idea of required spatial components to have animation components. A spatial component should mean "this entity is located at position (x,y) in our simulation". In my mind, that has nothing to do with animation. For me, animation is coupled with movement and actions. If we are moving right we loop an animation for moving right. If we swing a sword, we run the animation to swing a sword once. 

Side related note: If you have the urge to force two components to always be used together, that means it is time to make a new component that combines the two and delete to two previous ones or think differently.

**Comment by JaredPoetter** [comment]
Let's make sure I am understanding you correctly. The DirectionComponent is basically going to be used as a carrier pigeon to deliver the information of the sprite's current direction and action between the AnimationSystem and PlayerSystem/MonsterSystem. Or should the action be another component, ActionComponent?

**Comment by sturmE** [comment]
The direction component defines where the "front" of a sprite is. In the future, we may want to merge components together but for now this could be its own component.

My thought is that the system that moves and entity should set the direction the entity is facing and set the animation. Direction will probably be used in alot more places than just animation. It is independent of other systems, but if a system wants to know the direction they can look at it.

For animation, I feel like someone should explicitly set the animation of an entity instead of us inferring that what animation.

**Comment by sturmE** [comment]
I dont know if I answered your question.

**Comment by AOEChamp** [comment]
I believe this was resolved with #82
