### ISSUE TITLE
Fix Player Score Hit Rate Implementation

### ISSUE THREAD

**Issue by dawl** [4950/DirtyGame#250]
Hit Rate = Total Hits On Player / Total Number of Monster Attacks

**Comment by AOEChamp** [comment]
@fualkner @FourierTransformer @fluffybunnies 

Adeeb and I (Shak) were discussing the new "HitRate" and it's kinda janky. We didn't want to go with accuracy partially because it correlated with time. In essence we are now calculating the monster's accuracy, which again can vary greatly as dependent on time.

ie the longer you are in the game, the more enemies fire, the tinier your "hitrate" becomes.

Thoughts?

**Comment by bkern24** [comment]
How dependent are we on this accuaracy? I mean do we use it to calculate player score?

**Comment by FourierTransformer** [comment]
We were planning on using it to calculate player score. But it seems as if
there might be a few problems with it. Just wondering if it should be
scrapped or re-worked.

But since this is technically server side, and we can update sql tables
later, it's not crucial for play testing.

**Comment by AOEChamp** [comment]
Did we decide what to do about this?

**Comment by AOEChamp** [comment]
Nvm, looks like we dropped it

**Comment by FourierTransformer** [comment]
removed hit rate and couldn't come up with anything else.
