### ISSUE TITLE
Documentation on how to access and log into the server

### ISSUE THREAD

**Issue by JaredPoetter** [4950/DirtyGame#315]
We need access and documentation on how to access the server to be able to update code that is running on the server.

**Comment by AOEChamp** [comment]
There really isn't anything to access. Deployment should work from visual studio. Open the TowerSite project, go to publish. The publish profile should already be filled out

**Comment by Quillwerth** [comment]
Just tried to publish a very small change to the site. It's asking for credentials, I gave it the database ones. It did not work. I'm not aware of other creds we're to use. Perhaps you could send an email, @AOEChamp ?

**Comment by AOEChamp** [comment]
Hmm. Not sure what credentials it wants. Could be this: http://msdn.microsoft.com/en-us/library/ff683676.aspx

The easiest solution might be to add whoever needs access as a co-administrator to the Azure subscription. Then I'd assume you log in with your live id. Send me your Windows Live ID(or make one) and I'll add you.

**Comment by lingqingmeng** [comment]
Can you add me? I'm mengx061@outlook.com

**Comment by AOEChamp** [comment]
Added you. Trying logging in to WindowsAzure as well as publishing from
VS2013

**Comment by Quillwerth** [comment]
Please add me: pbseverin@outlook.com

**Comment by Quillwerth** [comment]
Ling and I just tried to publish, used our credentials, and got this error:

Error   2   Web deployment task failed. (Connected to the remote computer ("waws-prod-ch1-003.publish.azurewebsites.windows.net") using the Web Management Service, but could not authorize. Make sure that you are using the correct user name and password, that the site you are connecting to exists, and that the credentials represent a user who has permissions to access the site.  Learn more at: http://go.microsoft.com/fwlink/?LinkId=221672#ERROR_USER_UNAUTHORIZED.)     0   0   TowerSite

This needs to be resolved. Either we get access through our accounts, or you give us access to yours. This is needed as soon as possible, because we are _blocked_ on our tasks until then. @AOEChamp

**Comment by Quillwerth** [comment]
Also, did you have to download any updates, support packages, or any third party applications for Visual Studios, Azure, IIS? We want to match your configuration as closely as possible so we can get our publishing to work with our MS account credentials.

**Comment by AOEChamp** [comment]
There was an azure sdk, I believe I posted the info on the dev environment
page. Make sure you can log into windowsazure and manage the website. I
believe the publish profile has a spectate password that is not your live
id. If it is lot being filled out automatically, you will have to get VS to
fill it out for you. Either by downloading the publish profile online, or
through VS . You have admin access, so there's nothing more I can give you
in that regards

**Comment by Quillwerth** [comment]
Finally worked it out. I'm learning so much.

Step 1: manage.windowsazure.com, log-in.
Step 2: Go to Web Pages (sidebar) --> csci4950
Step 3: Click "Download the Publish Profile"

Step 4: In Visual Studio, with the TowerSite project open, right-click TowerSite --> Publish...
Step 5: On the pop-up's sidebar, click Profile --> Import...
Step 6: Select downloaded Import file.
Step 7: Click preview (sidebar) --> Publish
Step 8: Cry tears of joy when finally, finally, you don't get an authentication error.

**Comment by Quillwerth** [comment]
The above has been ported to the Wiki. Yaaaaay.

**Comment by AOEChamp** [comment]
The weird part is, the publish profile gets committed too. So it should
have just worked...
