### ISSUE TITLE
AoE Damage

### ISSUE THREAD

**Issue by sturmE** [4950/DirtyGame#36]
Right now we kill monsters by walking over them. Next, we want to kill monsters by explicitly attacking them.

How are we going to do this from a aoe damage perspective. What I mean by this is, you press a button, then we do damage to everything with a radius around you.

Thoughts?

**Comment by baylorw** [comment]
The designers need to decide how combat will work. In some games, combat moves to a separate screen. If it's on the same screen, combat could be by running into people but i think pressing a button is more common. Since we are not clamping to a grid, range is a factor. 

Yesterday i was discussing with a friend how we'd handle AoE in a Unity game. We're going to use a circular collision volume. In our system, collisions and triggers are the same, with a collision having a triggerEvent property. The object gets an event (either onCollision or onEnter/onStay/onExit) and responds to it by taking damage. The object generating the event has a drop off rate so that objects at the periphery can either take full damage or attenuated damage.

i don't know what monogame and we have for collision volumes/polys and triggers.

**Comment by Quillwerth** [comment]
Closed. We can attack monsters. We have hitboxes. We can do AOE.
