### ISSUE TITLE
Faster Placement

### ISSUE THREAD

**Issue by Quillwerth** [4950/DirtyGame#365]
I don't care how it's done, but I think Baylor has a point: it takes too long to get to your appropriate ELO. Either a high initial K factor, placement matches, or something else that  would move ELO faster for skilled players is a must, seeing how we'll probably only get a bit of time out of each player. @AOEChamp and @FourierTransformer may have ideas about this.

**Comment by lingqingmeng** [comment]
In Starcraft's dynamic placement matching service, a winning streak (5 or
so games in a row) results in a broadening "frontier". This frontier
doesn't actually improve the K factor for ELO scores, its specifically
implemented so people get *matched *with levels that the game deems
appropriate based on your ELO acceleration -> (d(dELO/dt) )/ dt. If you
(the player) keep beating these exponentially-increasing difficulty
matches, your ELO will naturally start growing faster obviously since your
large "frontier" is matching you up with super hard levels, sooner than a
person would if he's not on a massive winning streak.

**Comment by Quillwerth** [comment]
This is a good idea. I'll look into implementation.
