### ISSUE TITLE
Boundary box information in the spatial component

### ISSUE THREAD

**Issue by JaredPoetter** [4950/DirtyGame#55]
Put in the information on the sprites current size in the spatial component so that the collision is accurate.

Also put in so sort of way to change the box offset because the walking frame and attacking frames are not the same size. They also the attacking frames do not have the player in the center of the frame.

Sample code for the animation component:

```
//modify animation crap
//notice we changed size of sprite
if(e.HasComponent<Spatial>()) {
    //modify it
}
```

**Comment by bkern24** [comment]
I am reading through the basics of Farseer, and felt that this may apply here, especially the Shape and Fixtures

World 
The world object is the manager of it all. It iterates all the objects in the world each time you call the Step() function and makes sure everything is consistent and stable.

Body 
The body keeps track of world position. It is basically a point is space that is affected by forces such as impulses from collisions and gravity.

Shape 
A shape is what extends the point in space to a 2d shape in space. The centroid and stuff like area, inertia and mass is calculated for the shape.

Fixture 
A fixture attaches (fix) the shape to the body so that the centroid of the shape becomes the body’s position. Whenever you move the body, you also move the shape. Once a collision occur to the shape, the force is calculated and applied to the body.

**Comment by baylorw** [comment]
You could just make the bounding box the same size as the sprite (or the size of the initial sprite). i don't currently know any reason to have fine-grained collision for the game we're making and with limited time i'm not sure this would be high priority.

**Comment by sturmE** [comment]
I believe this was finished.
