### ISSUE TITLE
Implement new enemy: Wall Hugger

### ISSUE THREAD

**Issue by FourierTransformer** [4950/DirtyGame#92]
An enemy which glides around the border of the map boundaries and takes no ranged damage. When approached after a .5 sec delay, fires a dart up to 100px that slows the player to half speed for 5 secs it does 10 damage. It can fire again in 2 seconds. It can move 3x player speed. It has 25 health.

Every constant in this ticket should be easily modifiable, so that during play testing these can change if necessary.

**Comment by JaredPoetter** [comment]
I don't know if I am missing something but what is '100px'? I am sure that it will be obvious once you tell me but it is not clear to me. So maybe you want to clarify what you mean by 100px.

EDIT: Reading through the other tickets I figured out what you guys mean by '100px'. It is the number of pixels. This measurement might have to change to something like meters because I think that the physics system might be meters but the rendering is in pixels. Is that correct?

**Comment by dawl** [comment]
@bkern24 How does the physics system measure distance?

**Comment by FourierTransformer** [comment]
When we were creating the monsters, we didn't know how exactly radius
around the enemy/player is measured (in tiles or pixels), so we went with
pixels - so that's what it is referring to.

**Comment by JaredPoetter** [comment]
I can look into some of these different types of monsters. I will assign myself to the one I am currently working on.

**Comment by JaredPoetter** [comment]
@eric1989 I am just wanting to check in with you. What is the state of this monster? I know that the other developers are being slow in development but I have not see any code push to the repo from you about this monster. If you are having problems please let myself or  Conrad (@dawl) know ASAP.

**Comment by JaredPoetter** [comment]
Done
