### ISSUE TITLE
Implement new enemy: Grenadier

### ISSUE THREAD

**Issue by FourierTransformer** [4950/DirtyGame#95]
The grenadier walks around at .8x the player speed and lobs grenades at the player from within 500px. After the grenade lands, it goes off after 2 seconds and affects the player in the area (500px radius) by 20 health. He can lob a grenade once every 7 seconds. He scurries away from the player (.9x speed of the player) when the player is near (within 100px). 

Every constant in this ticket should be easily modifiable, so that during play testing these can change if necessary.

**Comment by JaredPoetter** [comment]
I can look into some of these different types of monsters. I will assign myself to the one I am currently working on.

**Comment by Duffman9205** [comment]
Here's how I'm thinking the monster's weapon will work:
1. Launch projectile that stops at range (instead of being destroyed)
2. after stopping, start a timer
3. when timer expires, detonate

if the projectile ever collides with the player, detonate

I've figured out how to create an AoE field by firing an event, but I'm having trouble figuring out the points leading up to firing it.
@AOEChamp , since you created the projectile system in the first place, do you have any ideas?

**Comment by FourierTransformer** [comment]
So @Duffman9205, there was a slight change that was done to this guy at today's meeting. If the player is within the max-distance of the grenade toss, the grenade should stop near the player. (aka trajectory's max distance is now how far the player is).

This way, grenades don't overshoot the player.
